version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: topicos-big-data
    restart: always
    environment:
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/media/lordstark/Development/www/python/dashboard/topicos_big_data
volumes:
  mysql-volume:
    driver: local